name: 'retail_analytics'
version: '1.0.0'
config-version: 2

profile: 'retail_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  retail_analytics:
    staging:
      +materialized: view
      +schema: STAGING
      +tags: ["staging"]
    marts:
      +materialized: incremental
      +schema: ANALYTICS
      +tags: ["marts"]
      +incremental_strategy: merge

vars:
  start_date: '2024-01-01'
  database: 'RETAIL_ANALYTICS_DB'
